### ISSUE TITLE
Does it preserve cookies?

### ISSUE THREAD

**Issue by JeffML** [jesseditson/superagent-relative#1]
I haven't tried this package, but I did use superagent-prefix until I discovered it didn't allow me to preserve cookies.  I wonder if this will suffer the same side-effect?

https://github.com/visionmedia/superagent/issues/1164

**Comment by jesseditson** [comment]
Yup, I had run in to this issue with superagent-prefix as well, this project explicitly forwards cookies (https://github.com/jesseditson/superagent-relative/blob/master/index.js#L6), so it should work for your purposes!
